### ISSUE TITLE
Serious Issue: User doesn;t exists

### ISSUE THREAD

**Issue by theankitjais** [redianmarku/instagram-follower-scraper#2]
Hey, brother!
I had got a project developed by you and it was well working but after 2 days, it started throwing error like:
```
USERS: ['alexandradaddario']
ERROR: Error getting user details for alexandradaddario. Please verify that the user exists.
```

Help me. I also texted on IG.

**Comment by fatihkabakk** [comment]
> Hey, brother!
> I had got a project developed by you and it was well working but after 2 days, it started throwing error like:
> 
> ```
> USERS: ['alexandradaddario']
> ERROR: Error getting user details for alexandradaddario. Please verify that the user exists.
> ```
> 
> Help me. I also texted on IG.

I have tried to scrape this user's followers, and did not face any errors. Can you give more information about the situation? Additionally, can you reinstall the repository and try using a virtual environment, please?

**Comment by fatihkabakk** [comment]
I think Instagram blocks users by account, in which case proxies would be useless. So, I think the solution is just to set a time limit or change accounts while changing proxies.

**Comment by fatihkabakk** [comment]
I couldn't get which exe you are talking about. There are not any executable programs at the moment. This repository only includes an interpretable file written in python.
