### ISSUE TITLE
NameError: name 'Service' is not defined

### ISSUE THREAD

**Issue by ajstahovec** [redianmarku/instagram-follower-scraper#21]
`bot = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
                                   ^^^^^^^
NameError: name 'Service' is not defined`

**Comment by lrcode97** [comment]
from selenium.webdriver.chrome.service import Service
you need this at the top

**Comment by ajstahovec** [comment]
> from selenium.webdriver.chrome.service import Service
> you need this at the top

added it. now I'm getting: 
`NameError: name 'ChromeDriverManager' is not defined`

**Comment by lrcode97** [comment]
Take away the bit that says ‘as CM’ at the top of the code I think

**Comment by ajstahovec** [comment]
Alright it at least runs after asking for the follower count, but now I'm getting
`selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"/html/body/div[4]/div/div/div[3]/div[2]/button"}
  (Session info: chrome=111.1.1111.11)`

*the session info is changed obviously.

**Comment by redianmarku** [comment]
New version released

**Comment by ajstahovec** [comment]
Using latest version. Still getting error:
`TypeError: object of type 'NoneType' has no len()`

**Comment by A1iAshoor** [comment]
Use my fork. It should work.
